# Generated by Django 2.0.2 on 2018-04-09 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='intrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.BooleanField(default=False)),
                ('Feature_Film_Production', models.BooleanField(default=False)),
                ('TV_Corporates_or_AV', models.BooleanField(default=False)),
                ('Filming_OR_Event_Permissions', models.BooleanField(default=False)),
                ('Augmented_Reality_Campaigns', models.BooleanField(default=False)),
                ('Third_Dimension_Design_OR_Modelling_OR_WalkThrough_Or_Animations', models.BooleanField(default=False)),
                ('IT_Consultancy', models.BooleanField(default=False)),
                ('Application_Devalopment_Or_Web_Designing', models.BooleanField(default=False)),
                ('Mobile_Application_Development', models.BooleanField(default=False)),
                ('Webcasting_Services_End_to_End', models.BooleanField(default=False)),
                ('Coperate_Identities_or_Brand_Building', models.BooleanField(default=False)),
                ('Creative_Consultancy', models.BooleanField(default=False)),
                ('Print_Designing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=280)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
